# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Set iOS platform version to 12.0 or higher as required by react-native-webrtc
platform :ios, '13.4'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'VideoCallAppReactNative' do
  config = use_native_modules!

  # Path to react-native is specified from the config
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Explicitly include react-native-webrtc
  pod 'react-native-webrtc', :path => '../node_modules/@videosdk.live/react-native-webrtc'

  target 'VideoCallAppReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Additional settings for the post-install phase
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # :ccache_enabled => true
    )
  end
end
